### ISSUE TITLE
appengine support

### ISSUE THREAD

**Issue by drewwells** [ainsleyc/factual-go-driver#1]
Appengine doesn't allow access to http.DefaultClient, so this driver fails to build on it. There appears to be some support for overriding the http.Client in go-oauth by making some low level.

This might be a good opportunity to switch to the semi-official oauth2 client https://github.com/golang/oauth2. What are your thoughts on this?

**Comment by ainsleyc** [comment]
Ah interesting. Unfortunately I don't have cycles to work on this at the moment, but would be happy to take a pull request.
